### ISSUE TITLE
泡泡机器人SLAM论坛申请转载文章

### ISSUE THREAD

**Issue by yvonshong** [YiChenCityU/Recent_SLAM_Research#1]
您好，我是泡泡机器人SLAM 论坛的成员，泡泡机器人SLAM是国内少有的免费分享SLAM知识和资源的社群和论坛，官网：http://paopaorobot.org/ ，致力于国内SLAM相关技术的推广和普及，请问能否转载这篇文章，我的个人wechat: Yvon-Shong 微信公众号：paopaorobot_slam

**Comment by YiChenCityU** [comment]
你好，可以转载，也就是我最近三四个月看文章后记录收集的。希望对大家有帮助。

**Comment by yvonshong** [comment]
您好 已转载 地址是 https://mp.weixin.qq.com/s/zur0VvY5tuBdMvlgGvrbog 欢迎关注我们的公众号～ 感谢～中秋快乐
（ps issue可以close啦
