### ISSUE TITLE
GAN网络与SLAM结合的文章有吗？

### ISSUE THREAD

**Issue by jinzhenmu** [YiChenCityU/Recent_SLAM_Research#14]
大佬，有木有关于GAN网络与SLAM结合的

**Comment by YiChenCityU** [comment]
好像比较少, GAN 用来path planning有人做

**Comment by FangGet** [comment]
Multi-Frame GAN: Image Enhancement for Stereo Visual Odometry in Low Light
GANVO: Unsupervised Deep Monocular Visual Odometry and Depth Estimation with Generative Adversarial Networks

这两篇算是吧

**Comment by jinzhenmu** [comment]
谢谢。我也找了GANVO  好像还有一篇sGANVO
