### ISSUE TITLE
Real-time 3D Mapping using a 2D Laser Scanner and IMU-aided Visual SLAM

### ISSUE THREAD

**Issue by gaojiejiejie** [YiChenCityU/Recent_SLAM_Research#9]
你好，之前看github，发现你在这篇文章Real-time 3D Mapping using a 2D Laser Scanner and IMU-aided Visual SLAM 的code下评论过，请问你有没有跑过相关的代码，就是关于IMU辅助SLAM的代码？可以分享一下吗？

**Comment by YiChenCityU** [comment]
不好意思刚看到,我没跑过这个代码.

**Comment by TouchDeeper** [comment]
@gaojiejiejie
你说的这篇论文有PR吗？
